repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        exclude: ^examples/
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^examples/
      - id: end-of-file-fixer
        exclude: ^examples/
      - id: trailing-whitespace
        exclude: ^examples/
      - id: check-yaml
        exclude: (^examples/|^cmd/hatchet-cli/cli/templates/)
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.7.2
    hooks:
      - id: golangci-lint
        args: ["--config=.golangci.yml"]
        exclude: ^examples/
