[files]
extend-exclude = [
    ".git/",
    "go.mod",
    "frontend/docs/pages/blog/*.json",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bwha-webhook-",
    "[0-9A-Za-z/+]{80}",
]

[default.extend-words]
datas = "datas"
strat = "strat"
