name: spelling
on: pull_request
jobs:
  spelling:
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: crate-ci/typos@master
        continue-on-error: true
