name: 'Close stale issues'
on:
  schedule:
    - cron: '0 8 * * *'

permissions:
  actions: write
  issues: write

jobs:
  stale:
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: 'This issue has been stale for 90 days. Please update the issue or comment to keep it active. Otherwise, it will be closed in 5 days.'
          days-before-stale: 90
          days-before-close: 5
          stale-issue-label: 'stale'
